service: meme-historian

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  region: ${opt:region, 'eu-north-1'}
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: sls-deploy-${opt:account, 'serverless'}-${self:provider.region}
    serverSideEncryption: AES256
  environment:
    DEFAULT_FOLDER: ${file(config/${self:provider.stage}.json):defaultFolder}
    S3_BUCKET_NAME: ${file(config/${self:provider.stage}.json):bucketName}-${self:provider.stage}
    LOG_LEVEL: ${file(config/${self:provider.stage}.json):logLevel}
  apiKeys:
    - meme-api-key
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:GetObject
        - s3:ListBucket
        - s3:ListObjectsV2
        - s3:PutObject
      Resource:
        - arn:aws:s3:::${self:provider.environment.S3_BUCKET_NAME}*
        - arn:aws:s3:::${self:provider.environment.S3_BUCKET_NAME}/*
    - Effect: "Allow"
      Action:
        - ses:SendEmail
      Resource: "*"

functions:
  uploadImage:
    handler: src/handler.uploadImage
    events:
      - http:
          path: album/folder/{folderName}
          method: post
          private: true
  folders:
    handler: src/handler.folders
    events:
      - http:
          path: album/folder
          method: get
          private: true
  getFolderContent:
    handler: src/handler.getFolderContent
    events:
      - http:
          path: album/folder/{folderName}
          method: get
          private: true

resources:
  - ${file(template.yml)}

plugins:
  - serverless-plugin-typescript
  - serverless-deployment-bucket
  - serverless-pseudo-parameters
  - serverless-plugin-include-dependencies
