Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:provider.environment.S3_BUCKET_NAME}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  SnsMail:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ${self:provider.environment.SNS_EMAIL_TOPIC_NAME}
      Subscription:
        - Endpoint: ${self:provider.environment.MAIL_RECEIVER}
          Protocol: Email